import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar';
import Footer from './Footer';

// Fonts
import { airStrikeBold, pressStart2P, airStrikeLaser } from "./styles/fonts";


const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${airStrikeLaser.variable}  ${airStrikeBold.variable} `}
      >
        <main className="text-white">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
