import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './(layout-design)/Navbar';
import Footer from './(layout-design)/Footer';
import BackgroundMesh from './(layout-design)/BackgroundMesh'

// Fonts
import { airStrikeBold, airStrikeLaser, corleoneDue, loveYa, poppins } from "./styles/fonts";




export const metadata = {
  title: 'School-Buddy',
  description: 'Generated by create next app',
  icons: {
    icon:'/public/assets/Home Vector.svg'
  }
}





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${loveYa.variable} ${corleoneDue.variable}, ${poppins.variable} `}
      >
        <main className="text-white  max-w-[1280px] w-[95vw] m-auto ">
          <BackgroundMesh />

          

          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
